spring:
#  devtools:
#    restart:
#      enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost:3306/com_ling_mybatis_begin}?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}

logging:
  level:
    com.ling.mybatis.begin: ${LOGGING_LEVEL_COM_DGLG:debug}

dglg:
  login:
    tokenSecret: dglg123
    tokenExpireSecond: 1800
    infoExpireSecond: 30

